# Site settings
title: 술 노트
email: admin@minibrary.com
description: 술 노트
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sool.minibrary.com" # the base hostname & protocol for your site
twitter_username: minibrary
github_username: minibrary
permalink: /:year/:month/:day/:title/
# this is the url root of the view source link on the footer page.
viewsourceroot: https://github.com/minibrary/sool/

# this is the url root of the create page link on the footer page.
newsourceroot: https://github.com/minibrary/sool/new/gh-pages

#########################################
# for duoshuo.com commenting system, uncomment following line if you do not want to include duoshuo.com. 
#duoshuo_shortname: lixizhi
#duoshuo_url: "http://lixizhi.github.io"
# disqus.com commenting system. please note that it is exclusive with duoshuo.com
disqus_shortname: minibrary
disqus_url: "http://sool.minibrary.com"
#########################################

# Build settings
markdown: kramdown

# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false
